### ISSUE TITLE
[Bug]音频加载延迟导致的字幕不同步

### ISSUE THREAD

**Issue by cha0sCat** [umonaca/kikoeru-quasar#6]
系统ios14 
浏览器chrome 
发生在切歌或跳进度时，如果网速较慢，导致音频加载迟缓，字幕就会先行一步

**Comment by cha0sCat** [comment]
可以通过 音频加载完成后暂停并继续播放，同步时间轴 来临时解决这个问题

**Comment by umonaca** [comment]
最近太忙顾不上改，你如果着急解决的话可以看一下[plyr的文档](https://github.com/sampotts/plyr)，主要关注`pause`和/或`stalled`两个Event，要改的文件是`AudioElement.vue`。  

另外目前的codebase没有适当的缓存机制，因为它原本是按局域网需求设计的。`canplay`时直接播放并不适合公网环境。  

还有就是关于浏览器兼容问题，可以通过改两个地方解决：`package.json`里的`browserlist`字段，改法参考[Quasar文档里的例子](https://quasar.dev/quasar-cli/browser-compatibility)和[browserlist文档](https://github.com/browserslist/browserslist)。`last 1 version`过于激进了。还有就是`quasar.conf`里的`modern: true`改成`false`。  

真正负责transpile的`@quasar/app`目前仍然锁定在1.x，升级到2.x可以提高兼容性，但是breaking changes太多暂时没有时间改。详情见[Quasar CLI文档](https://quasar.dev/quasar-cli/app-upgrade-guide)。  

另外提一点，提高兼容性是有速度代价的。polyfill越多越明显
